services:
  entradas-qr-lituam:
    build: .
    container_name: entradas-qr-lituam

    ports:
       - "127.0.0.1:8000:8000"

    volumes:
      - ./data:/app/data

    env_file:
      - .env

    restart: unless-stopped